sudo: required
services: 
  - docker

#build the docker image of client project for test execution using dev version of docker file
before_install: 
  - docker build -t chiri92/react-test -f ./client/Dockerfile.dev  ./client

#run the test for client 
scripts:
  - docker run -e CI=true chiri92/react-test npm test

#build docker image using production Dockerfile in order to push them to docker hub
after_success:
  - docker build -t chiri92/multi-client ./client
  - docker build -t chiri92/multi-nginx  ./nginx
  - docker build -t chiri92/multi-server ./server
  - docker build -t chiri92/multi-worker ./worker

#Login to docker hub inorder to push these above created images 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#take images & push to docker hub
  - docker push chiri92/multi-client
  - docker push chiri92/multi-nginx
  - docker push chiri92/multi-server
  - docker push chiri92/multi-worker


